CREATE TABLE HIBERNATE_DEVELOPERS(
   ID INT NOT NULL AUTO_INCREMENT,
   FIRST_NAME VARCHAR(50) DEFAULT NULL,
   LAST_NAME VARCHAR(50) DEFAULT NULL,
   SPECIALTY VARCHAR(50) DEFAULT NULL,
   SKILL  VARCHAR(50) DEFAULT NULL,
   ACCOUNT VARCHAR (50) DEFAULT NULL,
   PRIMARY KEY(ID)
);