
CREATE TABLE developer(
   id INT NOT NULL AUTO_INCREMENT,
   first_name VARCHAR(50) DEFAULT NULL,
   last_name VARCHAR(50) DEFAULT NULL,
   specialty VARCHAR(50) DEFAULT NULL,
   skill  VARCHAR(50) DEFAULT NULL,
   account VARCHAR (50) DEFAULT NULL,
   PRIMARY KEY(ID)
);